default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: blog_dev
  port: 5432

test:
  <<: *default
  database: blog_test
  port: 5432
